<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_etracker"
 *
 * Auto generated by Extension Builder 2017-03-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'RKW eTracker',
	'description' => 'Extension for reportings based on eTracker (see https://etracker.de)',
	'category' => 'plugin',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel,de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.4',
	'constraints' => array(
		'depends' => array(
            'extbase' => '6.2.0-7.6.99',
            'fluid' => '6.2.0-7.6.99',
            'typo3' => '6.2.0-7.6.99',
            'rkw_basics' => '7.6.10-7.6.99',
            'rkw_mailer' => '7.6.10-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);